import {execFileSync} from "node:child_process";
import {
    existsSync,
    readFileSync,
    writeFileSync,
} from "node:fs";
import path from "node:path";

const releaseVersionPattern = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/;
const textEntryPattern = /\.(?:css|html|js|json|md|svg|txt|xml|yaml|yml)$/i;
const requiredArchiveEntries = [
    "README.md",
    "README.zh-CN.md",
    "i18n/en.json",
    "i18n/zh-CN.json",
    "icon.png",
    "index.css",
    "index.js",
    "plugin.json",
    "preview.png",
];
const shortMarker = String.fromCharCode(65, 73);
const modelMarker = String.fromCharCode(71, 80, 84);
const libraryMarker = String.fromCharCode(76, 76, 77);
const restrictedMarkers = [
    {marker: ["Co", "dex"].join(""), scanBundledCode: true},
    {marker: ["Open", shortMarker].join(""), scanBundledCode: true},
    {marker: ["Chat", modelMarker].join(""), scanBundledCode: true},
    {marker: ["generated by ", shortMarker].join(""), scanBundledCode: true},
    {marker: modelMarker, scanBundledCode: false},
    {marker: shortMarker, scanBundledCode: false},
    {marker: libraryMarker, scanBundledCode: false},
];

const options = parseArguments(process.argv.slice(2));
const packageMetadata = readJson("package.json");
const pluginMetadata = readJson("plugin.json");
const version = packageMetadata.version;

assert(typeof version === "string" && releaseVersionPattern.test(version), "package.json must use an X.Y.Z version.");
assert(pluginMetadata.version === version, "package.json and plugin.json versions must match.");

if (options.tag) {
    assert(options.tag === `v${version}`, `Tag ${options.tag} does not match version ${version}.`);
    const releaseNotes = extractReleaseNotes(version);
    if (options.notesOutput) {
        writeFileSync(path.resolve(options.notesOutput), `${releaseNotes}\n`);
    }
} else {
    assert(!options.notesOutput, "--notes-output requires --tag.");
}

if (options.archive) {
    validateArchive(path.resolve(options.archive), pluginMetadata);
}

console.log(`Release metadata validated for ${version}.`);

function parseArguments(argumentsList) {
    const parsed = {};
    const supportedOptions = new Set(["--archive", "--notes-output", "--tag"]);

    for (let index = 0; index < argumentsList.length; index += 2) {
        const name = argumentsList[index];
        const value = argumentsList[index + 1];
        assert(supportedOptions.has(name), `Unknown option: ${name ?? "(missing)"}.`);
        assert(value && !value.startsWith("--"), `Option ${name} requires a value.`);
        parsed[name.slice(2).replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())] = value;
    }

    return parsed;
}

function readJson(filePath) {
    return JSON.parse(readFileSync(path.resolve(filePath), "utf8"));
}

function extractReleaseNotes(versionNumber) {
    const changelog = readFileSync(path.resolve("CHANGELOG.md"), "utf8");
    const escapedVersion = versionNumber.replaceAll(".", "\\.");
    const headingPattern = new RegExp(`^##\\s+${escapedVersion}(?:\\s+—[^\\r\\n]*)?\\s*$`, "m");
    const heading = headingPattern.exec(changelog);
    assert(heading, `CHANGELOG.md does not contain a ${versionNumber} release section.`);

    const notesStart = heading.index + heading[0].length;
    const nextHeadingOffset = changelog.slice(notesStart).search(/^##\s+/m);
    const notesEnd = nextHeadingOffset === -1 ? changelog.length : notesStart + nextHeadingOffset;
    const notes = changelog.slice(notesStart, notesEnd).trim();
    assert(notes.length > 0, `CHANGELOG.md section ${versionNumber} is empty.`);
    return notes;
}

function validateArchive(archivePath, sourcePluginMetadata) {
    assert(existsSync(archivePath), `Release archive not found: ${archivePath}.`);
    const entries = runUnzip(["-Z1", archivePath]).split(/\r?\n/).filter(Boolean);
    const uniqueEntries = new Set(entries);

    assert(entries.length === uniqueEntries.size, "Release archive contains duplicate paths.");
    entries.forEach((entry) => {
        const pathParts = entry.split("/");
        assert(!entry.startsWith("/"), `Release archive contains an absolute path: ${entry}.`);
        assert(!entry.includes("\\"), `Release archive contains a non-portable path: ${entry}.`);
        assert(!pathParts.includes(".."), `Release archive contains an unsafe path: ${entry}.`);
        assert(!entry.startsWith("dist/"), "Release files must be stored at the archive root, not under dist/.");
    });

    requiredArchiveEntries.forEach((entry) => {
        assert(uniqueEntries.has(entry), `Release archive is missing ${entry}.`);
    });

    const archivedPluginMetadata = JSON.parse(runUnzip(["-p", archivePath, "plugin.json"]));
    assert(
        archivedPluginMetadata.name === sourcePluginMetadata.name,
        "Archived plugin name does not match plugin.json.",
    );
    assert(
        archivedPluginMetadata.version === sourcePluginMetadata.version,
        "Archived plugin version does not match plugin.json.",
    );

    entries.filter((entry) => textEntryPattern.test(entry)).forEach((entry) => {
        const contents = runUnzip(["-p", archivePath, entry]);
        assert(
            !containsRestrictedMarker(contents, entry),
            `Release archive contains a restricted attribution marker in ${entry}.`,
        );
    });
}

function containsRestrictedMarker(contents, entry) {
    return restrictedMarkers.some(({marker, scanBundledCode}) => {
        if (!scanBundledCode && entry.toLocaleLowerCase().endsWith(".js")) {
            return false;
        }
        if (marker.length <= 3) {
            return new RegExp(`\\b${marker}\\b`, "i").test(contents);
        }
        return contents.toLocaleLowerCase().includes(marker.toLocaleLowerCase());
    });
}

function runUnzip(argumentsList) {
    return execFileSync("unzip", argumentsList, {
        encoding: "utf8",
        maxBuffer: 16 * 1024 * 1024,
    });
}

function assert(condition, message) {
    if (!condition) {
        throw new Error(message);
    }
}
